Define pydbus.Variant as a tuple, not dict #PSBM-149503
Otherwise the code fails on python3.6 (Vz7) with the following error:

...
File "/usr/lib64/python3.6/site-packages/gi/overrides/GLib.py", line 222, in _create_array
  (v, rest_format, _) = self._create(format[1:], args[0][i:])
TypeError: unhashable type: 'slice'

This commit is a fixup for 508da22e592 ("Fix to systemd overwriting cpu.shares
value #VSTOR-71016").

Signed-off-by: Andrey Drobyshev <andrey.drobyshev@virtuozzo.com>