policies: wfdbk: Fix div/0
  Terminating program due to unhandled exception:
  Traceback (most recent call last):
    File "/usr/lib64/python2.7/site-packages/vcmmd/util/threading.py", line 24, in run_with_except_hook
      run_original(*args2, **kwargs2)
    File "/usr/lib64/python2.7/threading.py", line 764, in run
      self.__target(*self.__args, **self.__kwargs)
    File "/usr/lib64/python2.7/site-packages/vcmmd/ldmgr/base.py", line 225, in _worker_thread_fn
      self._process_request()
    File "/usr/lib64/python2.7/site-packages/vcmmd/ldmgr/base.py", line 212, in _process_request
      req()
    File "/usr/lib64/python2.7/site-packages/vcmmd/ldmgr/base.py", line 247, in __call__
      ret = self.fn(*self.args, **self.kwargs)
    File "/usr/lib64/python2.7/site-packages/vcmmd/ldmgr/base.py", line 396, in activate_ve
      self._balance_ves()
    File "/usr/lib64/python2.7/site-packages/vcmmd/ldmgr/base.py", line 302, in _balance_ves
      stats_updated)
    File "/usr/lib64/python2.7/site-packages/vcmmd/ldmgr/policies/WeightedFeedbackBasedPolicy.py", line 200, in balance
      vepriv.update()
    File "/usr/lib64/python2.7/site-packages/vcmmd/ldmgr/policies/WeightedFeedbackBasedPolicy.py", line 104, in update
      self._update_weight()
    File "/usr/lib64/python2.7/site-packages/vcmmd/ldmgr/policies/WeightedFeedbackBasedPolicy.py", line 83, in _update_weight
      weight -= self._unused * self._UNUSED_FINE / self.quota
  ZeroDivisionError: float division by zero

PSBM-43855

Signed-off-by: Vladimir Davydov <vdavydov@virtuozzo.com>