Track active_vm number in the base KSMPolicy class #OVZ-7488
KSM policy relies on the number of currently active VMs.  Currently it's
being tracked by VZDensity, VZPolicyPerf policies, but not by the
NoOpPolicy, which leads to crash:

CRITICAL vcmmd: AttributeError: 'NoOpPolicy' object has no attribute 'active_vm'

All policies are derived classes of KSMPolicy: VZKsmPolicy(KSMPolicy),
NoOpPolicy(KsmPolicy(KSMPolicy)), VZDensity(NoOpPolicy).  So let's just
keep track of the active VMs number in the topmost class, which is
KSMPolicy, and its methods for VE (de)activation.

Signed-off-by: Andrey Drobyshev <andrey.drobyshev@virtuozzo.com>