Convert dict.items() to list while excluding keys from the dict
In Python 3.x we cannot simply delete keys from the dict we're iterating
over since dict.items() returns not a list object (as it was in Python 2.x)
but a special view object [1].  This leads to a RuntimeError:

Failed to connect to VCMMD: org.freedesktop.DBus.Python.RuntimeError: Traceback
(most recent call last):
...
  File "/usr/lib64/python3.6/site-packages/vcmmd/config.py", line 123, in _exclude
    for k, v in a_dict.items():
RuntimeError: dictionary changed size during iteration

Hence we use conversion of dict.items() to list as a workaround.

[1] https://docs.python.org/3/library/stdtypes.html#dict-views

PSBM-133879

Signed-off-by: Andrey Drobyshev <andrey.drobyshev@virtuozzo.com>